# vim:ft=sh
# Change bash prompt
# \w			Current directory
# \u			Current user
# \n			New line
# \h			Hostname
# [\033[00m		White color
# \033[01;32m[	Green color
PS1='\[\033[01;32m[\w]\n\u@\h\[\033[00m\]:\$ '
export PS1

if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

alias ls='ls -G'
alias ll='ls -AlFG'
alias la='ls -AG'
alias l='ls -CFG'
