"""""""""""""""""""""""""""""""""""""""""
"
"	Mateusduboli's VIMrc file
"
"""""""""""""""""""""""""""""""""""""""""

"	=> Be iMproved!
set nocompatible

"""""""""""""""""""""""""""""""""""""""""
"	=>	Scripts
"""""""""""""""""""""""""""""""""""""""""
"	=> Load Vim Bundles
source ~/.nvim/scripts/vundles.vim
"	=> Base configuration for all languages
source ~/.nvim/scripts/base.vim
"	=> Keyboard mappings
source ~/.nvim/scripts/keymap.vim
