ZSH=$HOME/.oh-my-zsh
ZSH_THEME="candy"
ZSH_CHAORDIC="$HOME/.zshrc-chaordic"
HEROKU_PATH="/usr/local/heroku/bin"
APP_BIN="$HOME/Applications/bin"
plugins=(git)

function prependToPath {
	export PATH="$1:$PATH"
}

function appendToPath {
	export PATH="$PATH:$1"
}

source $ZSH/oh-my-zsh.sh

### Source chaordic environment
if [ -e $ZSH_CHAORDIC ]; then
	source $ZSH_CHAORDIC
fi

### Added by the Heroku Toolbelt
prependToPath $HEROKU_PATH

### Added Applications/bin to PATH
prependToPath $APP_BIN

