[ -e "$HOME/.zshrc.before" ] && source "$HOME/.zshrc.before"

source ~/.antigen/antigen.zsh
antigen init ~/.antigenrc

export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'
ZSH_HOME="$HOME/.zsh"

for script in $ZSH_HOME/*.zsh; do
  source $script
done

test -e "${HOME}/.zshrc.local" && source "$HOME/.zshrc.local" # local environment configuration

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/mateus/Applications/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/mateus/Applications/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/mateus/Applications/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/mateus/Applications/google-cloud-sdk/completion.zsh.inc'; fi

if which pyenv 2>&1 >/dev/null; then
   eval "$(pyenv init --path)"
fi
