ZSH=$HOME/.oh-my-zsh
ZSH_THEME="candy"
ZSH_CHAORDIC="$HOME/.zshrc-chaordic"
HEROKU_PATH="/usr/local/heroku/bin"
APP_BIN="$HOME/Applications/bin"
plugins=(git)

source $ZSH/oh-my-zsh.sh

### Source chaordic environment
if [ -e $ZSH_CHAORDIC ]; then
	source $ZSH_CHAORDIC
fi

### Added by the Heroku Toolbelt
export PATH="$HEROKU_PATH:$PATH"

### Added Applications/bin to PATH
export PATH="$APP_BIN:$PATH"
