#!/bin/bash

BASE=$PWD
BACKUP=$PWD/backup
DOT_FILES=$BASE/dot_files
REPOS=$BASE/repositories


for file in $DOT_FILES/* ; do
	filename=$(basename $file)
	dest="$HOME/.$filename"
	echo "Saving : $dest"
	mv $dest "$BACKUP/$filename"
	ln -s $DOT_FILES/$filename $dest
done

# Install Vundle
git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
vim +BundleInstall +qall
