#!/bin/bash
BASE=$PWD
BACKUP=$PWD/backup
DOT_FILES=$BASE/dotfiles
REPOS=$BASE/repositories
MY_DIRS=("Workspace" "Virtual Machines" "Repositories" "Applications" "bin")

checkoutRepos() {
	echo "checkoutRepos"
}

updateRepos() {
	echo "updateRepos"
}

makeDirs() {
	for dir in $MY_DIRS ; do
		mkdir $dir
	done
}

linkFiles()
{
	mkdir $BACKUP
	for file in $DOT_FILES/* ; do
		filename=$(basename $file)
		dest="$HOME/.$filename"
		echo "Saving : $dest"
		mv $dest "$BACKUP/$filename"
		ln -s $DOT_FILES/$filename $dest
	done
}

installVim() {
	# Install Vundle
	CONQUE_BALL=conque_2.3.vmb
	mkdir tmp
	git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
	cd tmp && wget https://conque.googlecode.com/files/$CONQUE_BALL
	cd .. && rm -rf tmp
	vim +BundleInstall +"source tmp/$CONQUE_BALL" +qall
}

usage() {
	printf "Configuration management"
	printf "\nExample usage"
	printf "\nsetup [-h]"
	printf "\n\tThis menu."
	printf "\n-c"
	printf "\n\tCheckout\\Clone the repositories into the ~/Repositories folder"
	printf "\n-d"
	printf "\n\tCreate default directories in the user's home folder"
	printf "\n-i"
	printf "\n\tLink and Copy the link and copy folders into the user's home directory"
	printf "\n-u"
	printf "\n\tUpdate\\Pull the repositories on the ~/Repositories folder"
	printf "\n-g"
	printf "\n\tDiffs and copies the new files from the link and copy folders, into the user's home directory"
	printf "\n-r"
	printf "\n\tRemove the links installed in the user's home directory, and replaces then with the backups"
	printf "\n"
}

# If no arguments passed, then print usage and exit
if [ "$#" == 0 ]; then
	usage
	exit 1
fi

while getopts ":hicugr" OPTION; do
	case $OPTION in
		h)
			usage
			exit 1
			;;
		i)
			linkFiles
			installVim
			;;
		c)
			echo "Checkout Repos"
			;;
		u)
			echo "Update repos"
			;;
		g)
			echo "Upgrade"
			;;
		r)
			echo "Uninstall"
			;;
		?)
			usage
			exit 1
			;;
	esac
done
